---
title: "LDA report"
author: "Renata Diaz"
date: "10/12/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MATSS)
library(drake)
```

## Plot LDAS

```{r plot LDA, echo = F}
lda_results <- readd(lda_results)

for (i in seq(lda_results))
{
    print(names(lda_results)[i])
    if (names(lda_results)[i] == "lda_portal_data")
    {
       LDATS:::plot.LDA_VEM(lda_results[[i]][1][[1]], 
             xtime = drake::readd(portal_data_raw)$censusdate,
             xname = 'Year')
        title(main = names(lda_results)[i])
    } else {
        LDATS:::plot.LDA_VEM(lda_results[[i]][1][[1]], xname = 'Time step')
        title(main = names(lda_results)[i])
    }
    
}
```

## Summarize LDA results

```{r summarize LDA results}

lda_summary <- as.data.frame(names(lda_results))
lda_summary$ntopics <- NA
lda_summary$ntimeseries <- NA
lda_summary$ntimesteps <- NA

for(i in seq(lda_results)) {
    lda_summary$ntopics[i] <- lda_results[[i]][1]$k@k
    lda_summary$ntimeseries[i] <- as.integer(length(lda_results[[i]][1]$k@terms))
    lda_summary$ntimesteps[i] <- lda_results[[i]][1]$k@wordassignments$nrow
}

lda_summary

```

```{r plot lda summary, echo = F}

plot(lda_summary$ntimeseries, lda_summary$ntopics, main = 'Number of topics by number of timeseries', xlab = 'Number of timeseries', ylab ='Number of topics')

plot(lda_summary$ntimesteps, lda_summary$ntopics, main = 'Number of topics by length of timeseries',  xlab = 'Length of timeseries (number of timesteps)', ylab ='Number of topics')

```